version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/London"
    labels:
      - "chore"
    commit-message:
      prefix: "chore"
      include: "scope"
